//! Shared harness for exercising `#[tauri::command]` wrappers through the real
//! IPC deserialization path.
//!
//! The async wrapper body generated by tauri-macros deserializes every typed
//! argument with `CommandArg::from_command(CommandItem{..})?`. That `?`'s error
//! arm is attributed to the `#[tauri::command]` attribute line (the macro's
//! `Span::call_site`), so it shows up as a per-line `DA:0` even when the command
//! function body is fully covered — a classic region-attribution artifact
//! (waiver class W5). The arm is genuinely reachable, though: rejecting a body
//! that is missing its arguments makes `CommandArg::from_command` fail, which is
//! exactly the path the frontend hits when a caller passes a malformed payload.

use tauri::ipc::{CallbackFn, Invoke, InvokeBody};
use tauri::test::{get_ipc_response, mock_builder, mock_context, noop_assets, INVOKE_KEY};
use tauri::webview::InvokeRequest;
use tauri::WebviewWindowBuilder;

/// Build one mock app + webview registering `handler`, then reject an
/// empty-object body for every command in `cmds`. Each rejection must produce
/// an IPC error (covering the async wrapper's argument-deserialization error
/// arm) rather than a successful response.
pub fn assert_all_reject_bad_body(
    handler: impl Fn(Invoke<tauri::test::MockRuntime>) -> bool + Send + Sync + 'static,
    cmds: &[&str],
) {
    let app = mock_builder()
        .invoke_handler(handler)
        .build(mock_context(noop_assets()))
        .expect("build mock app");
    let webview = WebviewWindowBuilder::new(&app, "main", Default::default())
        .build()
        .expect("build webview");
    for cmd in cmds {
        assert_rejects(&webview, cmd, serde_json::json!({}));
    }
}

/// Like [`assert_all_reject_bad_body`], but with a caller-supplied body per
/// command. Multi-argument commands fail on their *first* missing key with the
/// empty-object body; that error arm is attributed to the function signature
/// line, so the `#[tauri::command]` attribute line stays `DA:0`. Supplying a
/// body that satisfies every argument except the *last* one makes the final
/// `CommandArg::from_command(..)?` fail, whose error arm lands on the
/// attribute line.
pub fn assert_all_reject_bodies(
    handler: impl Fn(Invoke<tauri::test::MockRuntime>) -> bool + Send + Sync + 'static,
    bodies: &[(&str, serde_json::Value)],
) {
    let app = mock_builder()
        .invoke_handler(handler)
        .build(mock_context(noop_assets()))
        .expect("build mock app");
    let webview = WebviewWindowBuilder::new(&app, "main", Default::default())
        .build()
        .expect("build webview");
    for (cmd, body) in bodies {
        assert_rejects(&webview, cmd, body.clone());
    }
}

fn assert_rejects(
    webview: &tauri::WebviewWindow<tauri::test::MockRuntime>,
    cmd: &str,
    body: serde_json::Value,
) {
    let response = get_ipc_response(
        webview,
        InvokeRequest {
            cmd: cmd.to_string(),
            callback: CallbackFn(0),
            error: CallbackFn(1),
            url: "tauri://localhost".parse().expect("url"),
            body: InvokeBody::Json(body),
            headers: Default::default(),
            invoke_key: INVOKE_KEY.to_string(),
        },
    );
    assert!(
        response.is_err(),
        "command {cmd} should reject a malformed body"
    );
}
