[package]
name = "future-rpc"
version = "0.0.0"
edition = "2021"

[lib]
name = "future_rpc"
path = "src/lib.rs"

[dependencies]
tonic.workspace = true
prost.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
prost-build.workspace = true
tonic-build.workspace = true
