import type { ExpoConfig } from "expo/config";
import { execFileSync } from "node:child_process";

function futureVersion(): string {
  return execFileSync(process.execPath, ["../scripts/version.mjs"], {
    cwd: __dirname,
    encoding: "utf8",
  }).trim();
}

const version = futureVersion();
const bundleVersion = version.split(/[-+]/)[0];
// Store build numbers (CFBundleVersion / Android versionCode) must be monotonic
// integers. CI injects FUTURE_BUILD_NUMBER (this workflow's own per-repo
// counter, starting at 1 — kept small because Android versionCode is an int32);
// local dev builds just use a constant — TestFlight/Play enforce monotonicity
// only, not that the number corresponds to any git commit.
const buildNumber = process.env.FUTURE_BUILD_NUMBER || "1";

const config: ExpoConfig = {
  name: "FutureOS",
  slug: "futureos",
  scheme: "futureos",
  version,
  orientation: "portrait",
  // iOS requires an opaque, full-bleed 1024px source. The desktop icon keeps
  // transparent padding for its own use, so use the mobile-specific crop here.
  icon: "./assets/icon.png",
  userInterfaceStyle: "light",
  plugins: [
    [
      "expo-camera",
      {
        cameraPermission: "Allow FutureOS to scan the desktop pairing QR code.",
        recordAudioAndroid: false,
      },
    ],
    [
      "expo-image-picker",
      {
        cameraPermission: "Allow FutureOS to take photos for conversation attachments.",
        photosPermission: "Allow FutureOS to select photos for conversation attachments.",
        microphonePermission: false,
      },
    ],
    [
      "expo-secure-store",
      {
        configureAndroidBackup: true,
        faceIDPermission: "Allow FutureOS to unlock remote credentials.",
      },
    ],
    "expo-localization",
    [
      "expo-build-properties",
      {
        android: {
          compileSdkVersion: 36,
          targetSdkVersion: 36,
          buildToolsVersion: "36.0.0",
        },
        ios: {
          deploymentTarget: "16.4",
        },
      },
    ],
  ],
  ios: {
    bundleIdentifier: "cn.futureos.mobile",
    buildNumber,
    supportsTablet: true,
    // React strings use expo-localization, but UIKit's editing menu (Paste,
    // AutoFill, etc.) chooses its language from the native bundle's declared
    // localizations. Declare the Chinese variants here so those system controls
    // follow a Chinese device/app language as well.
    infoPlist: {
      CFBundleLocalizations: ["en", "zh-Hans", "zh-Hant"],
    },
    // Required by expo-secure-store. Keep this in the Expo config because the
    // ios directory is generated by prebuild and is not version-controlled.
    entitlements: {
      "keychain-access-groups": ["$(AppIdentifierPrefix)$(CFBundleIdentifier)"],
    },
    config: {
      usesNonExemptEncryption: false,
    },
  },
  android: {
    package: "cn.futureos.mobile",
    versionCode: Number.parseInt(buildNumber, 10),
    permissions: ["android.permission.REQUEST_INSTALL_PACKAGES"],
    adaptiveIcon: {
      backgroundColor: "#0f172a",
      foregroundImage: "../desktop/src-tauri/icons/icon.png",
    },
    predictiveBackGestureEnabled: true,
  },
  extra: {
    futureVersion: version,
    bundleVersion,
    developmentPlatformUrl: "https://test.future-os.cn",
    productionPlatformUrl: "https://future-os.cn",
  },
};

export default config;
