package tui

// DefaultTheme returns the built-in dark theme.
func DefaultTheme() *Theme {
	return &Theme{
		Name:             "dark",
		Background:       "#1e1e2e",
		Foreground:       "#cdd6f4",
		Border:           "#45475a",
		BorderAccent:     "#89b4fa",
		BorderMuted:      "#313244",
		Accent:           "#89b4fa",
		UserColor:        "#89b4fa",
		AssistantColor:   "#cdd6f4",
		ThinkingColor:    "#7f849c",
		ThinkingText:     "#a6adc8",
		ToolColor:        "#ffffff",
		ToolPendingBg:    "#282832",
		ToolSuccessBg:    "#283228",
		ToolErrorBg:      "#3c2828",
		ErrorColor:       "#f38ba8",
		SystemColor:      "#a6e3a1",
		DiffAddColor:     "#a6e3a1",
		DiffDelColor:     "#f38ba8",
		Success:          "#a6e3a1",
		Warning:          "#f9e2af",
		Muted:            "#a6adc8",
		Dim:              "#7f849c",
		SelectedBg:       "#45475a",
		ContextGreen:     "#a6e3a1",
		ContextYellow:    "#f9e2af",
		ContextRed:       "#f38ba8",
		FooterBackground: "#181825",
		FooterForeground: "#a6adc8",
		InputBorder:      "#89b4fa",
		BashMode:         "#f9e2af",
		ThinkingOff:      "#5c6370",
		ThinkingMinimal:  "#6e6e6e",
		ThinkingLow:      "#5f87af",
		ThinkingMedium:   "#81a2be",
		ThinkingHigh:     "#b294bb",
		ThinkingXhigh:    "#d183e8",
		// Markdown colors
		MdHeading:         "#cba6f7",
		MdLink:            "#89b4fa",
		MdLinkUrl:         "#a6adc8",
		MdCode:            "#f9e2af",
		MdCodeBlock:       "#45475a",
		MdCodeBlockBorder: "#585b70",
		MdQuote:           "#a6adc8",
		MdQuoteBorder:     "#585b70",
		MdHr:              "#585b70",
		MdListBullet:      "#89b4fa",
		// Syntax colors
		SyntaxComment:  "#6c7086",
		SyntaxKeyword:  "#cba6f7",
		SyntaxFunction: "#89b4fa",
		SyntaxString:   "#a6e3a1",
		SyntaxNumber:   "#fab387",
		SyntaxType:     "#f9e2af",
		SyntaxVariable: "#cdd6f4",
		SyntaxConstant: "#fab387",
		SyntaxOperator: "#89dceb",
		// Additional UI
		UserMessageBg:   "#313244",
		UserMessageText: "#cdd6f4",
		ToolTitle:       "#ffffff",
		ToolOutput:      "#a6adc8",
	}
}

// LightTheme returns the built-in light theme.
func LightTheme() *Theme {
	return &Theme{
		Name:             "light",
		Background:       "#eff1f5",
		Foreground:       "#4c4f69",
		Border:           "#ccd0da",
		BorderAccent:     "#1e66f5",
		BorderMuted:      "#e6e9ef",
		Accent:           "#1e66f5",
		UserColor:        "#1e66f5",
		AssistantColor:   "#4c4f69",
		ThinkingColor:    "#9ca0b0",
		ThinkingText:     "#6c6f85",
		ToolColor:        "#df8e1d",
		ToolPendingBg:    "#e6e9ef",
		ToolSuccessBg:    "#dcedd6",
		ToolErrorBg:      "#f0d6dc",
		ErrorColor:       "#d20f39",
		SystemColor:      "#40a02b",
		DiffAddColor:     "#40a02b",
		DiffDelColor:     "#d20f39",
		Success:          "#40a02b",
		Warning:          "#df8e1d",
		Muted:            "#8c8fa1",
		Dim:              "#6c6f85",
		SelectedBg:       "#ccd0da",
		ContextGreen:     "#40a02b",
		ContextYellow:    "#df8e1d",
		ContextRed:       "#d20f39",
		FooterBackground: "#dce0e8",
		FooterForeground: "#5c5f77",
		InputBorder:      "#1e66f5",
		BashMode:         "#df8e1d",
		ThinkingOff:      "#9ca0b0",
		ThinkingMinimal:  "#8c8fa1",
		ThinkingLow:      "#1e66f5",
		ThinkingMedium:   "#6c6f85",
		ThinkingHigh:     "#7c3aed",
		ThinkingXhigh:    "#d946ef",
		// Markdown colors
		MdHeading:         "#8839ef",
		MdLink:            "#1e66f5",
		MdLinkUrl:         "#6c6f85",
		MdCode:            "#fe640b",
		MdCodeBlock:       "#ccd0da",
		MdCodeBlockBorder: "#bcc0cc",
		MdQuote:           "#8c8fa1",
		MdQuoteBorder:     "#bcc0cc",
		MdHr:              "#bcc0cc",
		MdListBullet:      "#1e66f5",
		// Syntax colors
		SyntaxComment:  "#9ca0b0",
		SyntaxKeyword:  "#8839ef",
		SyntaxFunction: "#1e66f5",
		SyntaxString:   "#40a02b",
		SyntaxNumber:   "#fe640b",
		SyntaxType:     "#df8e1d",
		SyntaxVariable: "#4c4f69",
		SyntaxConstant: "#fe640b",
		SyntaxOperator: "#04a5e5",
		// Additional UI
		UserMessageBg:   "#dce0e8",
		UserMessageText: "#4c4f69",
		ToolTitle:       "#df8e1d",
		ToolOutput:      "#6c6f85",
	}
}
