#!/usr/bin/env node
// Single source of truth for FutureOS build versioning.
//
// One input decides everything: whether the build is on a release tag.
//   - on a `vX.Y.Z` tag   → release, version = "X.Y.Z"
//   - anywhere else        → dev,     version = "0.0.0-dev.<short-git-hash>"
//
// The release/dev channel is DERIVED from the version string, not injected
// separately: a plain `X.Y.Z` (no `-` suffix) is a release; anything carrying a
// prerelease suffix (`-dev.…`) is a dev build. This keeps the model to a single
// injected value (FUTURE_VERSION) at the cost of one assumption:
//
//   ⚠️ Release versions must NEVER carry a `-` suffix. We intentionally do not
//   ship prerelease tags (e.g. `v1.2.3-rc.1`) — such a tag WOULD be misread as a
//   dev build. If prerelease releases are ever wanted, reintroduce an explicit
//   channel here and in the Rust/TS helpers instead of parsing the version.
//
// Config files stay pinned at 0.0.0; the real version is injected at build time
// from here (env FUTURE_VERSION → Rust build.rs, generated TS module, and the
// Tauri bundle version).

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";

/** Resolve the display version string for this build. */
export function resolveVersion() {
  // Explicit override (set by CI job env / Makefile) wins.
  if (process.env.FUTURE_VERSION) {
    return process.env.FUTURE_VERSION.trim();
  }
  // Release tag: refs/tags/vX.Y.Z → X.Y.Z
  const ref = process.env.GITHUB_REF || "";
  const tag = ref.match(/^refs\/tags\/v(\d+\.\d+\.\d+)$/);
  if (tag) {
    return tag[1];
  }
  // Dev build: 0.0.0-dev.<short-hash>
  let hash = "local";
  try {
    hash = execSync("git rev-parse --short HEAD", { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim() || "local";
  }
  catch {
    // No git (tarball build) — keep the "local" marker.
  }
  return `0.0.0-dev.${hash}`;
}

/** A version is a release iff it carries no prerelease/build suffix. */
export function isRelease(version) {
  return !version.includes("-");
}

/** Bundle/installer version — plain semver core (MSI/NSIS reject suffixes). */
export function bundleVersion(version) {
  return version.split(/[-+]/)[0];
}

// ─── CLI ─────────────────────────────────────────────────────────────────────

function patchJson(path, version) {
  const raw = readFileSync(path, "utf8");
  // Replace only the top-level "version" field, preserving formatting.
  const next = raw.replace(/("version"\s*:\s*)"[^"]*"/, `$1"${version}"`);
  writeFileSync(path, next);
}

function main() {
  const arg = process.argv[2];
  const version = resolveVersion();

  switch (arg) {
    case "--json":
      process.stdout.write(JSON.stringify({
        version,
        isRelease: isRelease(version),
        bundleVersion: bundleVersion(version),
      }));
      break;

    case "--github-output": {
      const out = process.env.GITHUB_OUTPUT;
      if (!out) {
        throw new Error("GITHUB_OUTPUT is not set");
      }
      const lines = [
        `version=${version}`,
        `is_release=${isRelease(version)}`,
        `bundle_version=${bundleVersion(version)}`,
      ].join("\n");
      writeFileSync(out, `${lines}\n`, { flag: "a" });
      break;
    }

    case "--gen-ts": {
      const out = process.argv[3];
      if (!out) {
        throw new Error("usage: version.mjs --gen-ts <path>");
      }
      writeFileSync(out, [
        "// Generated by scripts/version.mjs at build time — do not edit or commit.",
        `export const VERSION = ${JSON.stringify(version)};`,
        `export const IS_RELEASE = ${isRelease(version)};`,
        "",
      ].join("\n"));
      break;
    }

    case "--set-bundle": {
      // Patch the Tauri installer version to the plain semver core. The display
      // version (with -dev.<hash>) is injected separately via FUTURE_VERSION.
      const bundle = bundleVersion(version);
      // fileURLToPath (not .pathname) so this resolves correctly on Windows too.
      const root = fileURLToPath(new URL("../", import.meta.url));
      patchJson(`${root}gui/src-tauri/tauri.conf.json`, bundle);
      process.stderr.write(`tauri bundle version set to ${bundle}\n`);
      break;
    }

    default:
      // Bare invocation prints the version — handy for `$(node scripts/version.mjs)`.
      process.stdout.write(version);
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
