/**
 * Render-verification fixtures for the lean lane.
 *
 * `?leanRender=<mode>` swaps the conversation screen's timeline for a fixed
 * slice of the wire the desktop serves a client that declared
 * `lean_events_v1` — the declaration the shipping client makes
 * (`src/remote/client.ts`) — or, as the control, the same run as the full feed.
 *
 *   live         lean live lane, settled run (thinking / tool target / outcomes)
 *   live-mid     lean live lane, mid-run: a call in flight, reasoning open
 *   full-live    the same settled run as the full feed (control)
 *   history      lean history page (the durable read)
 *   full-history the same page as the full feed (control)
 *
 * The lean files are *generated by the shipping Rust trims* from the full ones
 * (`desktop/src-tauri`'s ignored `generate_render_fixtures` test, driven by
 * `scripts/screenshots/gen-lean-render-fixtures.mjs`), so the projection these
 * captures exercise is fed the bytes a phone would actually receive.
 *
 * The projection itself is the shipping one: the mock only replaces the
 * transport (see `RemoteContext`).
 */
import type { HistoryEntry, StreamEvent } from "../../src/remote/types";
import {
  applyStreamEvents,
  emptyTimeline,
  timelineFromEntries,
  type TimelineState,
} from "../../src/remote/projection";
import { asToolKind, normalizeArgs, targetFromArgs } from "@future-os/thread-projection";
import fullHistoryEntries from "./fixtures/render-full-history-entries.json";
import fullLaneEvents from "./fixtures/render-full-lane-events.json";
import leanHistoryEntries from "./fixtures/render-lean-history-entries.json";
import leanLaneEvents from "./fixtures/render-lean-lane-events.json";
import leanLaneMidEvents from "./fixtures/render-lean-lane-mid-events.json";

export type LeanRenderMode = "live" | "live-mid" | "full-live" | "history" | "full-history";

/**
 * The command (or path) the FULL feed carries for one call.
 *
 * Both lean slices drop a shell call's arguments, so the row fetches them when
 * it is opened: in the app that is the `get_tool_call_args` bridge round trip,
 * and the harness answers from the full fixture instead — the derivation is the
 * shipping one (`targetFromArgs`), so a capture shows the command the phone
 * would show after the same tap.
 *
 * Both full fixtures are searched because either lane can ask: a history row's
 * id comes from the persisted page, a live row's from the streamed
 * `tool_start`. In the app the answer comes from the agent's own database,
 * which holds the call whichever lane served the client.
 *
 * Null for a call neither full fixture knows, which is the app's "leave the row
 * as it was".
 */
export function leanTargetForToolCall(toolCallId: string): string | null {
  for (const entry of fullHistoryEntries as unknown as HistoryEntry[]) {
    for (const block of entry.blocks ?? []) {
      if (block.kind !== "tool_call" || block.toolCallId !== toolCallId) continue;
      return targetFromArgs(asToolKind(block.name ?? ""), normalizeArgs(block.arguments)) ?? null;
    }
  }
  for (const event of fullLaneEvents as unknown as StreamEvent[]) {
    if (event.type !== "tool_start") continue;
    let data: Record<string, unknown>;
    try {
      data = JSON.parse(event.data) as Record<string, unknown>;
    }
    catch {
      continue;
    }
    if (data.tool_id !== toolCallId) continue;
    const name = typeof data.tool_name === "string" ? data.tool_name : "";
    // The execution phase carries the arguments; the input phase never does.
    if (data.phase === "input") continue;
    return targetFromArgs(asToolKind(name), normalizeArgs(data.tool_args)) ?? null;
  }
  return null;
}

const MODES: LeanRenderMode[] = ["live", "live-mid", "full-live", "history", "full-history"];

/** The requested fixture slice, or null when the page did not ask for one. */
export function leanRenderMode(search: string): LeanRenderMode | null {
  const value = new URLSearchParams(search).get("leanRender");
  return MODES.find(mode => mode === value) ?? null;
}

/**
 * The timeline a mode renders, through the shipping reducers. Null means the
 * harness's own demo conversation (the page did not ask for a fixture slice).
 */
export function leanRenderTimeline(mode: LeanRenderMode | null): TimelineState | null {
  switch (mode) {
    case null:
      return null;
    case "history":
      return timelineFromEntries(leanHistoryEntries as unknown as HistoryEntry[]);
    case "full-history":
      return timelineFromEntries(fullHistoryEntries as unknown as HistoryEntry[]);
    case "live":
      return applyStreamEvents(emptyTimeline(), leanLaneEvents as unknown as StreamEvent[]);
    case "full-live":
      return applyStreamEvents(emptyTimeline(), fullLaneEvents as unknown as StreamEvent[]);
    case "live-mid":
      // Mid-run is not a prefix of the settled lane: the call in flight never
      // gets its outcome, and the reasoning block stays open.
      return applyStreamEvents(emptyTimeline(), leanLaneMidEvents as unknown as StreamEvent[]);
  }
}
