/**
 * Render-verification fixtures for the lean lane.
 *
 * `?leanRender=<mode>` swaps the conversation screen's timeline for a fixed
 * slice of the wire the desktop serves a client that declared
 * `lean_events_v1` — the declaration the shipping client makes
 * (`src/remote/client.ts`) — or, as the control, the same run as the full feed.
 *
 *   live         lean live lane, settled run (thinking / tool target / outcomes)
 *   live-mid     lean live lane, mid-run: a call in flight, reasoning open
 *   full-live    the same settled run as the full feed (control)
 *   history      lean history page (the durable read)
 *   full-history the same page as the full feed (control)
 *
 * The lean files are *generated by the shipping Rust trims* from the full ones
 * (`desktop/src-tauri`'s ignored `generate_render_fixtures` test, driven by
 * `scripts/screenshots/gen-lean-render-fixtures.mjs`), so the projection these
 * captures exercise is fed the bytes a phone would actually receive.
 *
 * The projection itself is the shipping one: the mock only replaces the
 * transport (see `RemoteContext`).
 */
import type { HistoryEntry, StreamEvent } from "../../src/remote/types";
import {
  applyStreamEvents,
  emptyTimeline,
  timelineFromEntries,
  type TimelineState,
} from "../../src/remote/projection";
import fullHistoryEntries from "./fixtures/render-full-history-entries.json";
import fullLaneEvents from "./fixtures/render-full-lane-events.json";
import leanHistoryEntries from "./fixtures/render-lean-history-entries.json";
import leanLaneEvents from "./fixtures/render-lean-lane-events.json";
import leanLaneMidEvents from "./fixtures/render-lean-lane-mid-events.json";

export type LeanRenderMode = "live" | "live-mid" | "full-live" | "history" | "full-history";

const MODES: LeanRenderMode[] = ["live", "live-mid", "full-live", "history", "full-history"];

/** The requested fixture slice, or null when the page did not ask for one. */
export function leanRenderMode(search: string): LeanRenderMode | null {
  const value = new URLSearchParams(search).get("leanRender");
  return MODES.find(mode => mode === value) ?? null;
}

/**
 * The timeline a mode renders, through the shipping reducers. Null means the
 * harness's own demo conversation (the page did not ask for a fixture slice).
 */
export function leanRenderTimeline(mode: LeanRenderMode | null): TimelineState | null {
  switch (mode) {
    case null:
      return null;
    case "history":
      return timelineFromEntries(leanHistoryEntries as unknown as HistoryEntry[]);
    case "full-history":
      return timelineFromEntries(fullHistoryEntries as unknown as HistoryEntry[]);
    case "live":
      return applyStreamEvents(emptyTimeline(), leanLaneEvents as unknown as StreamEvent[]);
    case "full-live":
      return applyStreamEvents(emptyTimeline(), fullLaneEvents as unknown as StreamEvent[]);
    case "live-mid":
      // Mid-run is not a prefix of the settled lane: the call in flight never
      // gets its outcome, and the reasoning block stays open.
      return applyStreamEvents(emptyTimeline(), leanLaneMidEvents as unknown as StreamEvent[]);
  }
}
